[theme]
primaryColor = "#4ea4ff"
backgroundColor = "#0f1419"
secondaryBackgroundColor = "#18202a"
textColor = "#e6edf3"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[global]
developmentMode = false