[theme]
primaryColor = "#4ea4ff"
backgroundColor = "#0f1419"
secondaryBackgroundColor = "#18202a"
textColor = "#e6edf3"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 50
enableStaticServing = false
allowRunOnSave = true
runOnSave = false
fileWatcherType = "auto"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[global]
developmentMode = false
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false

[runner]
magicEnabled = true