[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4ea4ff"
backgroundColor = "#0f1419"
secondaryBackgroundColor = "#18202a"
textColor = "#e6edf3"
base = "dark"

[client]
showErrorDetails = false