[server]
# Enable static file serving for CSS
enableStaticServing = true

# Disable file watching to prevent inotify limits
fileWatcherType = "none"
runOnSave = false

# Optimize for production deployment
port = 8501
address = "0.0.0.0" 
headless = true

# Memory and performance optimization (updated for 2025)
maxUploadSize = 5
maxMessageSize = 200
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
# Use custom CSS instead of built-in theming
base = "dark"
primaryColor = "#8B5CF6"
backgroundColor = "#0D0B14"
secondaryBackgroundColor = "#1A1825"
textColor = "#F8FAFC"

[client]
# Modern client configuration for 2025
showErrorDetails = false
toolbarMode = "minimal"

[global]
# Production optimizations
developmentMode = false
showWarningOnDirectExecution = false
suppressDeprecationWarnings = true

# Configuration cleaned - only valid Streamlit options