[theme]
primaryColor = "#4ea4ff"
backgroundColor = "#0f1419"
secondaryBackgroundColor = "#18202a"
textColor = "#e6edf3"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = false
maxUploadSize = 50
enableStaticServing = true
allowRunOnSave = true
runOnSave = false
fileWatcherType = "auto"
address = "0.0.0.0"
baseUrlPath = ""

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[global]
developmentMode = false
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false

[client]
caching = true
showErrorDetails = true
toolbarMode = "minimal"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true