[server]
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#8B5CF6"
backgroundColor = "#0D0B14"
secondaryBackgroundColor = "#1A1825"
textColor = "#F8FAFC"