# STREAMLIT CLOUD SECRETS CONFIGURATION
# Copy this content to your Streamlit Cloud app's secrets section

OPENAI_API_KEY = "your-openai-api-key-here"
OPENAI_MODEL = "gpt-4"
OPENAI_MAX_TOKENS = "4000"
OPENAI_TEMPERATURE = "0.7"

# Application Settings
APP_ENV = "production"
DEBUG_MODE = "False"
MAX_FILE_SIZE_MB = "50"
SESSION_TIMEOUT_MINUTES = "60"
API_RATE_LIMIT_PER_MINUTE = "60"
LOG_LEVEL = "INFO"