# STREAMLIT CLOUD SECRETS CONFIGURATION
# Copy this content to your Streamlit Cloud app's secrets section

# OpenAI Model Configuration
OPENAI_API_KEY = "your-openai-api-key-here"
OPENAI_MODEL = "gpt-4"
OPENAI_MAX_TOKENS = "12000"
OPENAI_TEMPERATURE = "0.7"

# Application Environment
APP_ENV = "production"
DEBUG_MODE = "False"

# Streamlit Cloud Optimized Limits
MAX_FILE_SIZE_MB = "5"
MAX_COMMENTS_PER_BATCH = "2000"

# Performance Optimization
CACHE_TTL_SECONDS = "300"
API_RATE_LIMIT_PER_MINUTE = "60"
SESSION_TIMEOUT_MINUTES = "30"

# Security Settings
SECRET_KEY = "your-secret-key-here"

# Logging Configuration
LOG_LEVEL = "INFO"

# API Rate Limiting
API_RATE_LIMIT_PER_DAY = "1000"

# Language Processing
DEFAULT_LANGUAGE = "es"
ENABLE_TRANSLATION = "True"

# Export Settings
EXCEL_MAX_ROWS = "10000"
EXPORT_COMPRESSION = "True"